[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npx prisma generate --schema=packages/database/schema.prisma",
  "npm run --workspace=packages/database build",
  "npm run --workspace=apps/api build"
]

[start]
cmd = "npx prisma migrate deploy --schema=packages/database/schema.prisma && cd apps/api && node dist/main"
